name: Deno Update

on:
  schedule:
    # every Saturday at 09:00 UTC (00:00 JST)
    - cron: "0 9 * * 6"
  workflow_dispatch:

jobs:
  update:
    permissions: write-all
    runs-on: ubuntu-slim

    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: create-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Setup repo
        uses: actions/checkout@v6
        with:
          token: ${{ steps.create-token.outputs.token }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: "~2.5"

      - name: Update dependencies with molt
        uses: hasundue/molt-action@v1
        with:
          token: ${{ steps.create-token.outputs.token }}
